var Web = {};
//= require "web/abstract_widget"
Web.AbstractWidget = AbstractWidget;
//= require "web/labelled_text"
Web.LabelledText = LabelledText;
//= require "web/progress_bar"
Web.ProgressBar = ProgressBar;
//= require "web/gui"
Web.GUI = WebGUI;
//= require "web/test_runner"
Web.TestRunner = WebTestRunner;
//= require "web/test_result"
Web.TestResult = WebTestResult;
